create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
create table cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table if exists `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table if exists hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key (cinema_id) references cinema (id);
alter table if exists place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key (hall_id) references hall (id);
alter table if exists session add constraint FKd38hyauvpulqx795f234oe049 foreign key (movie_id) references movie (id);
alter table if exists ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key (place_id) references place (id);
alter table if exists ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key (session_id) references session (id);
alter table if exists ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key (`user_id`) references `user` (id);
