create table if not exists cinema (id bigint not null auto_increment, address varchar(255) not null, email varchar(255) not null, name varchar(255) not null, phone varchar(255) not null, primary key (id)) engine=InnoDB;
create table if not exists hall (id bigint not null auto_increment, name varchar(255) not null, type varchar(255), cinema_id bigint not null, primary key (id)) engine=InnoDB;
create table if not exists movie (id bigint not null auto_increment, actors varchar(255), country varchar(255), description varchar(1000), director varchar(255), duration integer, genre varchar(255), poster_url varchar(255), release_date date, title varchar(255) not null, trailer_url varchar(255), primary key (id)) engine=InnoDB;
create table if not exists place (id bigint not null auto_increment, number integer not null, place_type varchar(255) not null, row integer not null, hall_id bigint not null, primary key (id)) engine=InnoDB;
create table if not exists session (id bigint not null auto_increment, session_date_time datetime(6) not null, hall_id bigint not null, movie_id bigint not null, primary key (id)) engine=InnoDB;
create table if not exists ticket (id bigint not null auto_increment, price decimal(38,2) not null, purchase_date datetime(6) not null, place_id bigint not null, session_id bigint not null, `user_id` bigint not null, primary key (id)) engine=InnoDB;
create table if not exists `user` (id bigint not null auto_increment, password varchar(255) not null, registration_date date, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table `user` add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table hall add constraint FKte75ikgkdmhfutuupvx2lhknr foreign key if not exists (cinema_id) references cinema (id);
alter table place add constraint FKi6xueble16lcu6ftbkb0jf0mf foreign key if not exists (hall_id) references hall (id);
alter table session add constraint FKdkbjq18dsn41qptljosa4cxk1 foreign key if not exists (hall_id) references hall (id);
alter table session add constraint FKd38hyauvpulqx795f234oe049 foreign key if not exists (movie_id) references movie (id);
alter table ticket add constraint FK7lqw2qck0hjiyt81t37u3qki4 foreign key if not exists (place_id) references place (id);
alter table ticket add constraint FK5x0dvk4itqbdpu2dxdo02b5f7 foreign key if not exists (session_id) references session (id);
alter table ticket add constraint FK5p81c2gthwqh9tes31r96txck foreign key if not exists (`user_id`) references `user` (id);
